### ISSUE TITLE
cargo-generate not updated & unclear it needs updating

### ISSUE THREAD

**Issue by s-mayrh** [leptos-rs/cargo-leptos#219] opened 2023-11-16 12:13 UTC
_Microsoft Windows [Version 10.0.19045.3693]
git version 2.42.0.windows.2
cargo 1.72.1 (103a7ff2e 2023-08-15)
cargo-leptos 0.2.2_

i am following the instructions written here:
https://leptos-rs.github.io/leptos/ssr/21_cargo_leptos.html

```
C:\Users\User Name\rust>cargo leptos new --git leptos-rs/start
 Project Name: leptos_actix_test
 Renaming project called `leptos_actix_test` to `leptos-actix-test`...
 Creating project called `leptos-actix-test`...
error: failed to find branch `master`
caused by: cannot locate local branch 'master'; class=Reference (4); code=NotFound (-3)
```

there is no 'master' branch, but a 'main' one:

```
C:\Users\User Name\rust>cargo leptos new --git leptos-rs/start -b main
 Project Name: leptos_actix_test
 Renaming project called `leptos_actix_test` to `leptos-actix-test`...
 Creating project called `leptos-actix-test`...
error: liquid: Cannot read file
cause: stream did not contain valid UTF-8
  with:
    path=C:\Users\User Name\rust\leptos-actix-test\assets\favicon.ico
```

at least something has been downloaded, but obviously that file isn't UTF-8.
same for the axum-template:

```
C:\Users\User Name\rust>cargo leptos new --git leptos-rs/start-axum
 Project Name: leptos_axum_test
 Renaming project called `leptos_axum_test` to `leptos-axum-test`...
 Creating project called `leptos-axum-test`...
error: failed to find branch `master`
caused by: cannot locate local branch 'master'; class=Reference (4); code=NotFound (-3)
```
```
C:\Users\User Name\rust>cargo leptos new --git leptos-rs/start-axum -b main
 Project Name: leptos_axum_test
 Renaming project called `leptos_axum_test` to `leptos-axum-test`...
 Creating project called `leptos-axum-test`...
error: liquid: Cannot read file
cause: stream did not contain valid UTF-8
  with:
    path=C:\Users\User Name\rust\leptos-axum-test\public\favicon.ico
```

i don't know if i can continue from here on or if something is missing now

**Comment by gbj** [comment] 2023-11-17 14:32
I don't have access to Windows but can't reproduce on another platform. 

This part of `cargo-leptos` just calls out to `cargo-generate`. If you run `cargo generate https://github.com/leptos-rs/leptos` do you get the same error? If so, what is your `cargo-generate --version`? It might be a bug in `cargo-generate`, or in how our template is set up.

**Comment by s-mayrh** [comment] 2023-11-29 20:24
right, updated `cargo-generate` from **0.2.1** to **0.18.5** ... it works now

that version was almost to-the-day **five years** old and i'm puzzled that it survived on my system that long o_O

i don't close the issue yet because there's no way i could have come up with this in the first place. i think:
 * either the installation of `cargo-leptos` hasn't defined a minimum version to update `cargo-generate`
 * or the leptos book is missing a note about updating this

btw on my ubuntu VPS there is no cargo-generate at all and it seems not to be required for `cargo leptos new` to work.

**Comment by benwis** [comment] 2024-01-12 01:15
We've updated the deps on the starter template, I think we can close this for now. Feel free to comment if this is still an issue

**Closed by benwis** 2024-01-12 01:15 UTC
