### ISSUE TITLE
How to run in Docker? IE I need a sample `Dockerfile`

### ISSUE THREAD

**Issue by dessalines** [leptos-rs/cargo-leptos#173] opened 2023-07-31 22:25 UTC
I'm having trouble getting a cargo-leptos app to run in docker. 

The binaries created by `cargo leptos build` *seem* to run, but I must be missing something, because the app is still unavailable. I can only seem to get leptos working with `cargo leptos serve`

**Comment by gbj** [comment] 2023-08-01 16:12
Here a link to [the Dockerfile for the Leptos website](https://github.com/leptos-rs/leptos-website/blob/main/Dockerfile). Ignore the fact that it's using a fork of `cargo-leptos`, this was relevant a few months ago when it was last deployed.

This uses `cargo-leptos` to build the app, then copies the relevant files and runs the binary itself. Any other issue may be something between you and whatever's hosting it? Maybe the issue is visible in the logs there? (for example, I find that on fly.io if I forget to change the `site-addr` to `0.0.0.0:8080` it just hangs in the browser, but logs a message in my Fly dashboard)

**Comment by aperepel** [comment] 2023-08-02 20:47
I wonder if it would make sense to include a `Dockerfile` in example projects by default. Or, perhaps, have it automatically generated via the `new` wizard?

**Comment by dessalines** [comment] 2023-08-03 15:25
Thanks, that's hugely helpful. I eventually did find [a working one](https://git.torrents-csv.ml/heretic/torrents-csv-leptos/src/branch/main/docker/Dockerfile), but it doesn't seem as good as yours, I'll update.

100% agree that it'd be nice to put either that `Dockerfile` in this codebase, or in docs somewhere.

**Comment by Th3Whit3Wolf** [comment] 2023-10-12 17:23
I also needed one and found [this one](https://github.com/Kanerix/portfolio-rs/blob/ba53d05a4507f4adb7556abb774da8ca37dfb18e/Dockerfile) particularly helpful for building static binaries.

**Comment by benwis** [comment] 2024-01-12 01:17
Closing as we have sample Dockerfiles in the Leptos book

**Closed by benwis** 2024-01-12 01:17 UTC
